# Generated by Django 5.0 on 2023-12-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discount",
            old_name="percentage",
            new_name="percent_off",
        ),
    ]
