# Generated by Django 5.0 on 2023-12-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_rename_percentage_discount_percent_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="сумма скидки"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="percent_off",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="процент скидки"
            ),
        ),
    ]
