# Generated by Django 5.0 on 2023-12-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_discount_amount_alter_discount_percent_off"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discount",
            old_name="amount",
            new_name="amount_off",
        ),
    ]
