# Generated by Django 5.0 on 2023-12-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_discount_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.ManyToManyField(blank=True, null=True, to="payments.discount"),
        ),
    ]
