# Generated by Django 5.0 on 2023-12-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_remove_order_discount_order_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="discount",
            new_name="discounts",
        ),
    ]
