# Generated by Django 5.0 on 2023-12-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_rename_discount_order_discounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discounts",
            field=models.ManyToManyField(to="payments.discount"),
        ),
    ]
