# Generated by Django 5.0 on 2023-12-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_alter_order_discounts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tax",
            old_name="rate",
            new_name="percentage",
        ),
        migrations.AddField(
            model_name="tax",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="описание"),
        ),
        migrations.AddField(
            model_name="tax",
            name="display_name",
            field=models.CharField(
                default="НДС", max_length=20, verbose_name="название"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tax",
            name="inclusive",
            field=models.BooleanField(default=True, verbose_name="включен"),
            preserve_default=False,
        ),
    ]
