# Generated by Django 5.0 on 2023-12-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_remove_order_tax_order_tax_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="страна"
            ),
        ),
    ]
