# Generated by Django 5.0 on 2023-12-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_tax_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="amount_off",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="сумма скидки"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="currency",
            field=models.CharField(default="USD", max_length=3, verbose_name="валюта"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="discount",
            name="percent_off",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="процент скидки"
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                check=models.Q(("percent_off__gte", 0)), name="percent_off_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                check=models.Q(("percent_off__lte", 100)), name="percent_off_max_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_off__gte", 0)), name="amount_off_positive"
            ),
        ),
    ]
