# Generated by Django 5.0 on 2023-12-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(default="USD", max_length=3, verbose_name="валюта"),
            preserve_default=False,
        ),
    ]
